name: Build and upload Rust binary to GitHub Releases
description: GitHub Action for building and uploading Rust binary to GitHub Releases

inputs:
  bin:
    description: Comma-separated list of binary names (non-extension portion of filename) to build and upload
    required: true
  archive:
    description: Archive name (non-extension portion of filename) to be uploaded (variables `$bin`, `$target`, `$tag`, and any string)
    required: false
    default: '$bin-$target'
  target:
    description: Target name, default is host triple
    required: false
  features:
    description: Comma-separated list of cargo build features to enable
    required: false
  tar:
    description: On which platform to distribute the `.tar.gz` file (all, unix, windows, or none)
    required: false
    default: 'unix'
  zip:
    description: On which platform to distribute the `.zip` file (all, unix, windows, or none)
    required: false
    default: 'windows'
  include:
    description: >
      Comma-separated list of additional files to be included to archive.
      Note that glob pattern is not supported yet.
    required: false
  leading_dir:
    description: Whether to create the leading directory in the archive or not
    required: false
    default: 'false'
  build_tool:
    description: Tool to build binaries (cargo or cross)
    required: false
  checksum:
    description: Comma-separated list of algorithms to be used for checksum (sha256, sha512, sha1, or md5)
    required: false

runs:
  using: node16
  main: main.js
