name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@e6a1170cbd07eb898017958967912976fce18f2d # 2026.7.3
    permissions:
      security-events: write # for github/codeql-action/*

  # TODO: test container
  test:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            bin-leading-dir: bin
            debug-archive: true
            leading-dir: true
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            package: test-crate
          - os: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            build-tool: cargo
            package: test-crate,test-crate
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu.2.17
            build-tool: cargo-zigbuild
          - os: macos-latest
            checksums: sha256,sha512,sha1,md5
          - os: macos-latest
            checksums: |
              sha256
              sha512
              sha1
              md5
            target: x86_64-apple-darwin
            workspace: true
          - os: macos-latest
            checksums: sha256 sha512 sha1 md5
            debug-archive: true
            target: aarch64-apple-darwin
          - os: macos-latest
            checksums: sha256, sha512, sha1, md5
            target: universal-apple-darwin
          - os: macos-latest
            checksums: sha256,sha512,sha1,md5
            target: universal-apple-darwin
            build-tool: cargo
          - os: windows-latest
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: windows-11-arm
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2.82.0
        with:
          tool: rust@stable
          fallback: none
      - uses: taiki-e/setup-cross-toolchain-action@3d9770ce98eb7dbcf378563182a5e8031165f75b # v1.41.0
        with:
          target: ${{ matrix.target }}
          runner: none
        if: matrix.target != '' && matrix.build-tool == 'cargo'
      - run: |
          cargo new --bin test-crate
          cat >| test-crate/src/main.rs <<'EOF'
          #[unsafe(no_mangle)]
          #[inline(never)]
          pub extern "C" fn debug_archive_test() {
              std::hint::black_box(());
          }

          fn main() {
              debug_archive_test();
          }
          EOF
      - uses: ./
        id: upload-rust-binary-action
        with:
          dry-run: true
          bin: test-crate
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build-tool }}
          no-default-features: true
          all-features: true
          package: ${{ matrix.package }}
          workspace: ${{ matrix.workspace || 'false' }}
          checksum: ${{ matrix.checksums || 'b2,sha256,sha512,sha1,md5' }}
          tar: all
          tar-xz: all
          zip: all
          manifest-path: test-crate/Cargo.toml
          debug-archive: ${{ matrix.debug-archive || 'false' }}
          leading-dir: ${{ matrix.leading-dir || 'false' }}
          bin-leading-dir: ${{ matrix.bin-leading-dir }}
          codesign: '-'
          codesign-prefix: 'com.example.'
          codesign-options: 'runtime'
      - name: Check action outputs
        run: |
          printf 'outputs.archive should not be empty\n'
          test -n "${OUTPUT_ARCHIVE}"

          printf 'outputs.zip should be a file\n'
          test -f "${OUTPUT_ZIP}"

          printf 'outputs.tar should be a file\n'
          test -f "${OUTPUT_TAR}"

          printf 'outputs.tar-xz should be a file\n'
          test -f "${OUTPUT_TAR_XZ}"

          printf 'outputs.sha256 should be a file\n'
          test -f "${OUTPUT_SHA256}"

          printf 'outputs.sha512 should be a file\n'
          test -f "${OUTPUT_SHA512}"

          printf 'outputs.sha1 should be a file\n'
          test -f "${OUTPUT_SHA1}"

          printf 'outputs.md5 should be a file\n'
          test -f "${OUTPUT_MD5}"

          if [[ "${DEBUG_ARCHIVE}" == "true" ]]; then
            printf 'outputs.debug-archive should be a file\n'
            test -f "${OUTPUT_DEBUG_ARCHIVE}"
            grep "$(basename -- "${OUTPUT_DEBUG_ARCHIVE}")" "${OUTPUT_SHA256}" >/dev/null
          fi
        env:
          OUTPUT_ARCHIVE: ${{ steps.upload-rust-binary-action.outputs.archive }}
          OUTPUT_ZIP: ${{ steps.upload-rust-binary-action.outputs.zip }}
          OUTPUT_TAR: ${{ steps.upload-rust-binary-action.outputs.tar }}
          OUTPUT_TAR_XZ: ${{ steps.upload-rust-binary-action.outputs.tar-xz }}
          OUTPUT_DEBUG_ARCHIVE: ${{ steps.upload-rust-binary-action.outputs.debug-archive }}
          OUTPUT_SHA256: ${{ steps.upload-rust-binary-action.outputs.sha256 }}
          OUTPUT_SHA512: ${{ steps.upload-rust-binary-action.outputs.sha512 }}
          OUTPUT_SHA1: ${{ steps.upload-rust-binary-action.outputs.sha1 }}
          OUTPUT_MD5: ${{ steps.upload-rust-binary-action.outputs.md5 }}
          DEBUG_ARCHIVE: ${{ matrix.debug-archive || 'false' }}
      - name: Check debug archive
        if: ${{ matrix.debug-archive }}
        env:
          BIN_LEADING_DIR: ${{ matrix.bin-leading-dir }}
          LEADING_DIR: ${{ matrix.leading-dir || 'false' }}
          OUTPUT_ARCHIVE: ${{ steps.upload-rust-binary-action.outputs.archive }}
          OUTPUT_DEBUG_ARCHIVE: ${{ steps.upload-rust-binary-action.outputs.debug-archive }}
          OUTPUT_TAR: ${{ steps.upload-rust-binary-action.outputs.tar }}
        run: |
          mkdir -- extracted
          tar -xf "${OUTPUT_TAR}" -C extracted
          tar -xf "${OUTPUT_DEBUG_ARCHIVE}" -C extracted
          debug_prefix=''
          if [[ "${LEADING_DIR}" == "true" ]]; then
            debug_prefix="${OUTPUT_ARCHIVE}/"
          fi
          if [[ -n "${BIN_LEADING_DIR}" ]]; then
            debug_prefix+="${BIN_LEADING_DIR}/"
          fi
          binary="extracted/${debug_prefix}test-crate"

          case "${RUNNER_OS}" in
            Linux)
              debug="extracted/${debug_prefix}test-crate.debug"
              test -f "${debug}"
              binary_sections="$(objdump -h "${binary}")"
              debug_sections="$(objdump -h "${debug}")"
              if grep '\.debug_info' <<<"${binary_sections}" >/dev/null; then
                exit 1
              fi
              grep '\.debug_info' <<<"${debug_sections}" >/dev/null
              readelf --string-dump=.gnu_debuglink "${binary}" |
                grep 'test-crate.debug' >/dev/null
              address="$(
                nm --defined-only "${binary}" |
                  awk '$3 == "debug_archive_test" { address = $1 }
                    END { print address }'
              )"
              test -n "${address}"
              addr2line -e "${binary}" "0x${address}" |
                grep '/test-crate/src/main.rs:' >/dev/null
              ;;
            macOS)
              debug="extracted/${debug_prefix}test-crate.dSYM"
              test -d "${debug}"
              binary_uuid="$(xcrun dwarfdump --uuid "${binary}" | awk '{ print $2 }')"
              debug_uuid="$(xcrun dwarfdump --uuid "${debug}" | awk '{ print $2 }')"
              test -n "${binary_uuid}"
              test "${binary_uuid}" = "${debug_uuid}"
              load_commands="$(otool -l "${binary}")"
              if grep '__DWARF' <<<"${load_commands}" >/dev/null; then
                exit 1
              fi
              load_address="$(
                awk '
                  $1 == "segname" && $2 == "__TEXT" { text = 1; next }
                  text && $1 == "vmaddr" && !address { address = $2 }
                  END { print address }
                ' <<<"${load_commands}"
              )"
              address="$(
                nm -nm "${binary}" |
                  awk '$4 == "_debug_archive_test" { address = $1 }
                    END { print address }'
              )"
              dwarf=("${debug}/Contents/Resources/DWARF/"*)
              test -n "${load_address}"
              test -n "${address}"
              test "${#dwarf[@]}" -eq 1
              xcrun atos \
                -arch arm64 \
                -o "${dwarf[0]}" \
                -l "${load_address}" \
                "0x${address}" |
                grep 'main.rs:' >/dev/null
              ;;
            *) exit 1 ;;
          esac
      - name: Check b2 output
        if: ${{ contains(matrix.checksums || 'b2,sha256,sha512,sha1,md5', 'b2') }}
        run: |
          printf 'outputs.b2 should not be empty\n'
          test -n "${OUTPUT_B2}"
        env:
          OUTPUT_B2: ${{ steps.upload-rust-binary-action.outputs.b2 }}
