name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

jobs:
  create-release:
    if: github.repository_owner == 'taiki-e'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: release
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: $version
          branch: 'main|v[0-9]+'
          token: ${{ secrets.GITHUB_TOKEN }}
