name: Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be increased
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    if: github.repository_owner == 'taiki-e'
    uses: taiki-e/github-actions/.github/workflows/action-release.yml@main
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    with:
      version: ${{ inputs.version }}
